version: '3'

services:
  php:
    build: docker/php
    container_name: "click-php"
    environment:
      TIMEZONE: Europe/Kiev
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    working_dir: /var/www

  webserver:
    image: nginx:1.13
    container_name: "click-nginx"
    depends_on:
      - php
    volumes:
      - ./:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80

  mysql:
    image: percona/percona-server:5.7
    container_name: "click-mysql"
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - ./var/data/mysql:/var/lib/mysql
    user: "1000:50"
